### ISSUE TITLE
Crash on single device

### ISSUE THREAD

**Issue by SergeHaddad** [DylanVann/DatePickerCell#22]
I'm beta testing my app through TestFlight, and it crashes on a single device (iPhone 7 Plus on iOS 10.3.3) whenever i set the date for the picker cell.

`pickerCell.datePicker.date = dateFormatter.date(from: savedDate!)!`

The app does not crash and works perfectly on all simulators, and even on other real devices, such as another iPhone 7 Plus on iOS 10.3.3. It only crashes on that person's device. Why is that?

**Comment by DylanVann** [comment]
I did find an issue on `10.3.3`. It was going into a loop in `heightForRowAt` ([fix here](https://github.com/DylanVann/DatePickerCell/commit/10212962b54a021640dd157a5b92edea67a8e8d4)). So that might be related to your issue, although it doesn't sound like it would be.

Aside from that I can't replicate the issue in the simulator. Sorry.

**Comment by DylanVann** [comment]
Closing for now. I'll reopen if you have a stack trace or something to go off of.
